version: "3.9"

services:
  redis:
    image: redis:7
    container_name: example-voting-app-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: example-voting-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data

  vote:
    build: ./vote
    container_name: example-voting-app-vote
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5000:80"

  result:
    build: ./result
    container_name: example-voting-app-result
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:80"

  worker:
    build: ./worker
    container_name: example-voting-app-worker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  db-data:
